let ids = [];
let allKeys = [];
let keys;
const largeSize = "350px";
const smallSize = "100px";
let titles;
let activeHash;

function setup(){
  noCanvas()
  generateContent()
  largePhotosFxn()
}

function draw(){
  checkActive()
}

function checkActive(){
  $(activeHash).css({
        // 'background-color': 'red',
        'color': 'lightgreen',
    });
}



function generateContent(){
  keys = Object.keys(photos);
  keys.forEach(function(key){
    allKeys.push(key)
    const photoGroup = photos[key]
    const box = createDiv()
    box.id(key)
    innerContent(photoGroup, key)
    buildList(key)
    addListFunction(key)
    let hash = '#'+key
    $(`${hash}`).hide();
  })

}



function addListFunction(key){
  let hash_li = '#'+key+'_li'
  $(hash_li).click(function() {
  activeHash = hash_li
// deselect/hide other li options and dives
    let arr_lis = allKeys.filter(value => value !== key);
    arr_lis.forEach(function(key){
      let hash_li = '#'+key+'_li'
      $(hash_li).css({
            'color': '',
        });
      $(hash_li).hover( function(){
        $(hash_li).css({
          'color': 'lightgray',
          'cursor':'pointer'
        })
        }, function(){
        $(hash_li).css({
          'color': '',
        })
        }
      )
// select other divs and hide
      let hash= '#'+key
      $(`${hash}`).hide();
    })

    // select clicked LI element
    $(hash_li).css({
          // 'background-color': 'red',
          'color': 'lightgreen',
      });
    // select associated div and show
    let hash = '#'+key
    $(`${hash}`).show();

})

}


function largePhotosFxn(){
    ids.forEach(function(id){
      const hash = '#'+id
      $(document).ready( () => {
        hideLarge(id)
      })
      $(hash).mouseover( () => {
        showLarge(id)
      // console.log(id)
      });
      $(hash).mouseout( () => {
        hideLarge(id)
      });
    })
  }


function buildList(id){
  const list = document.getElementById('titles')
  const element = document.createElement("LI");
  const id2 = id+'_li'
  element.innerHTML = id
  element.setAttribute("id", id2);
  list.appendChild(element);
}

function innerContent(photos,key){
  // looping through JSON photos object generated by generateFileList and creating
  // mini divs for thumbnails, and img object elements for the large images
  // this attached IDs to all elements for use later

  photos.forEach(function(file,i){
    // console.log(file)
  if (file.includes(smallSize)){
    // console.log(file)
    const name = file.substring(0,file.length-10)
    const div = document.createElement("div")
    const id = `${name}`
    const img = document.createElement("img")
    img.setAttribute("src","/static/" + key + "/" + file)
    $(img).attr('id',id)
    const objTo = document.getElementById(key)
    // console.log(objTo)
    objTo.appendChild(img)
    ids.push(id)
    // console.log(id)
  } else if(file.includes(largeSize)){
    // console.log(file)
    const name = file.substring(0,file.length-6)
    const img = createImg("/static/" + key + "/" + file)
    const id = `${name}`
    img.id(id)
    const hash = '#'+id
    $(hash).parent().css({position: 'relative'});
    $(hash).css({top: 120, left: 410, position:'absolute'});
  }
  })
}

function showLarge(id){
  keys.forEach(function(key){
    const array = photos[key]
    array.forEach(function(file,i){
    if(file.includes(id) && file.includes("350px")){
      const name = file.substring(0,file.length-6);
      const hash = '#'+name;
      // console.log(hash)
      $(`${hash}`).show();
    }
  })
})
}


function hideLarge(id){
  keys.forEach(function(key){
    const array = photos[key]
    array.forEach(function(file,i){
    if(file.includes(id) && file.includes("350px")){
      const name = file.substring(0,file.length-6);
      const hash = '#'+name;
      // console.log(hash)
      $(`${hash}`).hide();
    }
  })
})
}
